WebStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using WebStore.Domain.Abstract;
using WebStore.Domain.Entities;
using WebStore.WebUI.Models;
using WebStore.Domain.Entities.Authorization;
using WebStore.Domain.Concrete;

namespace WebStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private EFDbContext _db = new EFDbContext();
        private IProductRepository repository;
        private IOrdersRepository ordersRepository;
        private IUserRepository userRepository;
        public CartController(IProductRepository repo, IOrdersRepository ordersRepo, IUserRepository userRepo)
        {
            repository = repo;
            ordersRepository = ordersRepo;
            userRepository = userRepo;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            if(User.Identity.IsAuthenticated)
            { 
            User user = userRepository.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            ViewBag.UserID = user.Id;
            }
            return View(new Order());
        }

        [HttpPost]
        [Authorize]
        public ViewResult Checkout(Cart cart, Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.OrderLines = new List<OrderLine>();
                foreach (CartLine line in cart.Lines)
                {
                    order.OrderLines.Add(new OrderLine { Order = order, Product = line.Product, Quantity = line.Quantity });
                }
                ordersRepository.SaveOrder(order);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(order);
            }
        }
        [Authorize]
        public ActionResult UserOrder()
        {
            User user = userRepository.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            IEnumerable<Order> orders = ordersRepository.Orders.Where(o => o.UserId == user.Id);
            return View(orders);
        }
    }
}

WebStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Domain.Abstract;

namespace WebStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            this.repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
              .Select(x => x.Category)
              .Distinct()
              .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

WebStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Domain.Abstract;
using WebStore.Domain.Entities;
using WebStore.WebUI.Models;

namespace WebStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 5;
        
        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }
        
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products.Where(p => category == null || p.Category == category)
                  .OrderBy(p => p.ProductID)
                  .Skip((page - 1) * PageSize)
                  .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

WebStore.WebUI/Views/Shared/ProductSummary.cshtml
@model WebStore.Domain.Entities.Product

<div class="item">
    @if (Model.ImageData != null)
    {
        <div style="float: left; margin-right: 20px">
            <img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
        </div>
    }
    <h3>@Model.Name</h3>
    @Model.Description
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.HiddenFor(x => x.ProductID)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <input type="submit" value="+ Add to cart" />
    }

    <h4>@Model.Price.ToString("c")</h4>
</div>

WebStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.8.2.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <div class="float-right">
            <section id="login">
                @Html.Partial("_LoginPartial")
            </section>
        </div>
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">TEST MAGAZINE</div>
    </div>
    <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - KirkAwo Application Test</p>
            </div>
        </div>
    </footer>
</body>
</html>